import type { Metadata, Viewport } from "next";
import { Manrope } from "next/font/google";
import "./globals.scss";
import Footer from "./components/Footer";
import NavBar from "./components/NavBar";
import ScrollTheme from "./components/ScrollTheme";
import { SessionProvider } from "./lib/use-session";

const manrope = Manrope({
    subsets: ["latin"],
    variable: "--font-manrope",
    display: "swap",
});

export const viewport: Viewport = {
    themeColor: "#000000",
    colorScheme: "dark",
    width: "device-width",
    initialScale: 1,
    viewportFit: "cover",
};

export const metadata: Metadata = {
    title: "Expansive Mind",
    description: "Generated by Meredith Staton",
    appleWebApp: {
        capable: true,
        statusBarStyle: "black-translucent",
        title: "Expansive Mind",
    },
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en" className={manrope.variable}>
            <body className="antialiased">
                <SessionProvider>
                    <ScrollTheme />
                    <NavBar />
                    <div className="main-content">{children}</div>
                    <Footer />
                </SessionProvider>
            </body>
        </html>
    );
}
