import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.scss";
import { CookiesProvider } from "next-client-cookies/server";
import Footer from "./components/Footer";
import NavBar from "./components/NavBar";
import Image from "next/image";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
    title: "Expansive Mind",
    description: "Generated by Meredith Staton",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body className={`${inter.className} antialiased`}>
                <div className="mobile-only-message">
                    <Image
                        src="/brainlogo.svg"
                        alt="brain logo"
                        width={60}
                        height={60}
                    />
                    Mobile view is not ready yet. Please use on desktop :)
                </div>
                <CookiesProvider>
                    <NavBar />
                    <div className="main-content">{children}</div>
                    <Footer />
                </CookiesProvider>
            </body>
        </html>
    );
}
