import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.scss";
import { CookiesProvider } from "next-client-cookies/server";
import Footer from "./components/Footer";
import NavBar from "./components/NavBar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
    title: "Expansive Mind",
    description: "Generated by Meredith Staton",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body className={`${inter.className} antialiased`}>
                <CookiesProvider>
                    <NavBar />
                    <div className="main-content">{children}</div>
                    <Footer />
                </CookiesProvider>
            </body>
        </html>
    );
}
